[package]
name = "tvserver"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.4", features = ["headers", "ws", "http2", "macros", "tokio"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0.59"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "any", "sqlite", "migrate"] }
tower-http = { version = "0.3.0", features = ["fs", "trace", "cors"] }
tower = { version = "0.4.10", features = ["util"] }
tokio-util = "0.7.4"
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
async-trait = "0.1.64"
http = {path = "./private/http-0.2.8"}

[profile.release]
strip = "debuginfo"
