# if getting an error WARN[0000] container xxx.xxx is missing com.docker.compose.container-number label
# use `docker system prune -af`
version: '3.7'

services:
  tvserver:
    build:
      context: .
      network: host
    volumes:
      - .:/opt/tvserver
      - ${HOME}/Movies:/Movies
      - .transmission/config:/config
      - .transmission/downloads:/downloads
      - .transmission/watch:/watch
    env_file:
      - .env
    restart: on-failure
    stop_grace_period: 1s
    ports:
      - 80:80
  transmission:
    image: linuxserver/transmission:3.00-r8-ls150
    container_name: transmission
    environment:
      - PUID="${UID}"
      - PGID=1000
      - TZ=Etc/UTC
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PWD}
    env_file:
      - .env
    volumes:
      - .transmission/config:/config
      - .transmission/downloads:/downloads
      - .transmission/watch:/watch
    ports:
      - target: 9091
        published: 9091
      - target: 51413
        published: 51413
        mode: host
    restart: unless-stopped

#
#networks:
#  hostnet:
#    external: true
#    name: host