name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v3
    - name: Setup | Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        components: clippy
    - name: Install
      run: make install
    - name: Build
      run: make build
    - name: Run tests
      run: make test
